export const GET_STORY = 'GET_STORY';
export const GET_STORY_FAILURE = 'GET_STORY_FAILURE';
export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';

export const GET_STORIES = 'GET_STORIES';
export const GET_STORIES_FAILURE = 'GET_STORIES_FAILURE';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';

export const GET_PAGE = 'GET_PAGE';
export const GET_PAGE_FAILURE = 'GET_PAGE_FAILURE';
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const AUTHENICATE = 'AUTHENICATE';
export const AUTHENICATE_FAILURE = 'AUTHENICATE_FAILURE';
export const AUTHENICATE_SUCCESS = 'AUTHENICATE_SUCCESS';

export const REGISTER = 'REGISTER';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
