# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Novella' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for Novella
  pod 'Fabric'
  pod 'Crashlytics'
  #pod 'OneSignal', '>= 2.5.2', '< 3.0'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
  ]


  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'yoga'
      target.build_configurations.each do |config|
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
